# This workflow sets the package version for user agent
# when pull request to main branch is opened
# it takes pull request name
# and automatically commit it as a package version
# pull request name should always be a version of a new release
# 
# After version bump publishing Cocoapods release

name: cd

on:
  pull_request:
    branches: [ main, develop ]
env:
  PACKAGE_VERSION: ${{ github.event.pull_request.title }}

jobs:
  set-user-agent:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Set User Agent
        shell: bash
        run: ./.github/scripts/set-user-agent.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Set User Agent
          tagging_message: $PACKAGE_VERSION
          skip_checkout: true

      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push WalletConnectSwiftV2.podspec

