name: ci

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:    
    runs-on: macos-12
    strategy:
      matrix:
        test-type: [unit-tests, integration-tests, build-example-wallet, build-example-dapp]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.1

    - uses: actions/cache@v2
      with:
        path: |
          .build
          SourcePackagesCache
          DerivedDataCache
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Resolve Dependencies
      shell: bash
      run: make resolve_packages

    - uses: ./.github/actions/ci
      with:
        project-id: ${{ secrets.PROJECT_ID }}
